name: Storybook to GH-Pages

on: push

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
          run: echo Hello, world!
