name: Deploy to GitHub Pages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v1

      - name: Build
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        run: |
          yarn
          yarn storybook-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
